### ISSUE TITLE
Add path prefix to default json file since swaggerJSON is not guaranteed to be created in root path/给json文件添加默认路径

### ISSUE THREAD

**Issue by daiqing2009** [Cody2333/koa-swagger-decorator#1]
`  router.swagger = (options) => {
    // 设置swagger路由
    router.get('/swagger-json', async (ctx) => {
      ctx.body = buildSwaggerJson(options);
    });
    router.get('/swagger-html', async (ctx) => {
      ctx.body = swaggerHTML('/swagger-json');
    });
  };`
in above method, swagger json can be generated in paths other than root path, e.g. under /api/swagger-json.
我的代码API分3个文件，分别置于/api,/auth,/upload目录下，只希望暴露/api目录下的文件

**Comment by Cody2333** [comment]
给 router.swagger(options)添加了两个配置参数,更新一下依赖即可：

- swaggerJsonEndpoint
- swaggerHtmlEndpoint

eg.
```
router.swagger({
  swaggerHtmlEndpoint: '/swagger-html', // define your swagger endpoint here
  swaggerJsonEndpoint: '/swagger-json',
  ...
});
```

**Comment by daiqing2009** [comment]
多谢🙏，几乎完美了
