### ISSUE TITLE
在最新的版本文档中未看到Authorize如何配置，请问这一块如何配置？

### ISSUE THREAD

**Issue by jack-hate-titanic** [Cody2333/koa-swagger-decorator#182]

**Comment by Cody2333** [comment]
可以参考 example 里面的实现
1. 定义 SecuritySchemas：
https://github.com/Cody2333/koa-swagger-decorator/blob/main/example/schemas/extra.ts#L7
2. 在 routeConfig 装饰器中声明 security 字段
https://github.com/Cody2333/koa-swagger-decorator/blob/main/example/controller/demo.ts#L10

**Comment by jack-hate-titanic** [comment]
好的，感谢作者
