### ISSUE TITLE
如何使用 swagger 插件和主题？

### ISSUE THREAD

**Issue by luozhihua** [Cody2333/koa-swagger-decorator#27]
现在swagger 插件和主题支持自定义吗？

**Comment by Cody2333** [comment]
现在并不支持。
https://github.com/Cody2333/koa-swagger-decorator/blob/master/lib/swaggerHTML.ts swagger 的 html 模板定义在这里

**Comment by Cody2333** [comment]
欢迎提交 PR，之前我也没有仔细了解过 swagger 的主题和插件。

**Comment by o70078** [comment]
![image](https://user-images.githubusercontent.com/19776935/48113593-8dfdea80-e296-11e8-9444-3c5b48d4ba3c.png)
我在我的工程里引用了这个插件,不过当我tsc的时候,爆出了这么个异常.是我的配置问题吗...
