### ISSUE TITLE
可以为responses装饰器的参数添加一个类型的描述吗？

### ISSUE THREAD

**Issue by jerry4718** [Cody2333/koa-swagger-decorator#28]
因为我想在ts的项目中使用这个库，
但是用到responses装饰器的时候，会通过参数的默认值，将responses装饰器的参数推断为{ 200: { description: string }}，因而在我想描述500这个状态码的时候，编辑器中会出现错误提示

**Comment by Cody2333** [comment]
[v1.5.10](https://github.com/Cody2333/koa-swagger-decorator/tree/v1.5.10) 修复了这个问题

**Comment by jerry4718** [comment]
非常感谢非常感谢，这样我就不用提PR那么麻烦了哈哈哈
