### ISSUE TITLE
使用koa 如何在 实现文档

### ISSUE THREAD

**Issue by wxh0716** [Cody2333/koa-swagger-decorator#30]
通过 app.use(controller());  
function addControllers(router, dir) {
    fs.readdirSync(__dirname + '/' + dir).filter((f) => {
        return f.endsWith('.js');
    }).forEach((f) => {
        logger.info(`process controller: ${f}...`);
        let mapping = require(__dirname + '/' + dir + '/' + f);
        addMapping(router, mapping);
    });
}

module.exports = function (dir) {
    let
        controllers_dir = dir || 'controllers',
        router = require('koa-router')();
    addControllers(router, controllers_dir);
    return router.routes();
};

接口是这么实现的 
const remote=require('../base/middleware/client')
module.exports = {
    'POST /client': async (ctx, next) => {
        try {
            let data=ctx.request.body;
            let result=await remote.remote('ETL','words',null)
            let str=result.data;
            ctx.body= 'get data from'+str;
        }catch(e){
            logger.error(e.message);
        }
        next();
    }
};

这样来实现接口的  我只想实现接口文档  应该怎么弄？

**Comment by Cody2333** [comment]
请参考 swagger-jsdoc
