### ISSUE TITLE
TS2339: Property 'routes' does not exist on type 'SwaggerRouter'.

### ISSUE THREAD

**Issue by jerry4718** [Cody2333/koa-swagger-decorator#31]
我看到源码中，SwaggerRouter 已经是继承了Koa的Router，我觉得这个问题的原因可能是SwaggerRouter继承了wrapper.ts中的引入的Router而不是IRouter，因为我在这样改进后他就不再提示这个信息了

**Comment by Cody2333** [comment]
你的代码怎么实现的？
SwaggerRouter 继承了 koa.Router ，是包含 router.routes() 的方法的，我测试也没有报错
```
import { SwaggerRouter } from 'koa-swagger-decorator';
const router = new SwaggerRouter();
// router.swagger({...})
router.routes();
```

**Comment by jerry4718** [comment]
大概是我用法不正确，或者这边ts的配置有差别，总之我另外新建了一个项目就没有再出现这个问题

**Comment by lynzz** [comment]
tsconfig 的 compilerOptions 要设置 esModuleInterop  为 true, 就不会提示这个错误

可现有项目这个属性为 true ，也会报其它错误，好尴尬。

**Comment by juliopiubello** [comment]
I'm having the same problem, of typescript acusing 
[ts] Property 'routes' does not exist on type 'SwaggerRouter'. [2339]
and the router.swagger({ ... is exactly like the example

It is indeed a problem with ts, but hard to know what/how

**Comment by qszhu** [comment]
`esModuleInterop: true` is needed in `tsconfig.json` (#38 #61)

I think this prevents easy integration with existing projects without this option. At least this should be mentioned in the documentation.

**Comment by MarekZhang** [comment]
I was having the same issue, and it turned out that I forgot to install @types/koa-router

`npm i --save-dev @types/koa__router` saved the problem
