### ISSUE TITLE
引用后无法tsc,在koa-route里找不到route

### ISSUE THREAD

**Issue by o70078** [Cody2333/koa-swagger-decorator#38]
![image](https://user-images.githubusercontent.com/19776935/48113593-8dfdea80-e296-11e8-9444-3c5b48d4ba3c.png)
我在我的工程里引用了这个插件,不过当我tsc的时候,爆出了这么个异常.是我的配置问题吗...

**Comment by o70078** [comment]
我感觉和某些npm库的版本有问题. 或者tsconfig.json之类的配置文件问题.
我的tsconfig.json是这么写的:
`{
	"compileOnSave": true,
	"compilerOptions": {
		"module": "commonjs",
		"target": "es6",
		"moduleResolution": "node",
		//"sourceMap": true,
		//"emitDecoratorMetadata": true,
		//"pretty": true,
		//"declaration": true,
		"experimentalDecorators": true,
		"lib": [
			"es2017"
		],
		"rootDirs": [
			"./src"
		],
		"baseUrl": ".",
		"outDir": "./build",
		"paths": {
			"*": [
			  "node_modules/*",
			  "lib/types/*"
			]
		  }
	},
	"include": [
		"./src/**/*.ts"
	]
}`

tslint.json:

`
{
	"rules": {
			"no-duplicate-variable": true,
			"no-unused-variable": [
					true
			]
	}
}
`

**Comment by Cody2333** [comment]
tsconfig.json 需要设置 `esModuleInterop: true`

**Comment by o70078** [comment]
我去,居然解决了- - 这个参数是啥,居然搜索不到中文解释
