### ISSUE TITLE
参数校验中，需要一个nullable的配置项

### ISSUE THREAD

**Issue by jerry4718** [Cody2333/koa-swagger-decorator#49]
我设定了一个参数的类型为string，需要通过这个参数传入null来清空数据，但是null会导致没法校验为string

**Comment by Cody2333** [comment]
严格来说 null 不属于 string 类型，可以考虑直接不传这个参数字段来清空数据？

**Comment by jerry4718** [comment]
> 严格来说 null 不属于 string 类型，可以考虑直接不传这个参数字段来清空数据？

其他能符合string校验的值，都没有这种可以用来置空的含义啊，

**Comment by Cody2333** [comment]
前端传的时候就不传这个字段不可以吗？

**Comment by Cody2333** [comment]
https://github.com/Cody2333/koa-swagger-decorator/pull/65
添加了一个 nullable 的选择
