### ISSUE TITLE
issue in compileing the ramda  in nodemodule 

### ISSUE THREAD

**Issue by nirajbisht** [Cody2333/koa-swagger-decorator#61]
node_modules/koa-swagger-decorator/dist/decorators.d.ts:1:8 - error TS1192: Module '"/home/appinventiv/Desktoep/Backend/node_modules/@types/ramda/index"' has no default export.

1 import _ from 'ramda';
use in decorators.ts file as 
import  * as _ from 'ramda'
![issue](https://user-images.githubusercontent.com/37511770/56730564-f02fa680-6775-11e9-81b1-e60e88594536.png)

**Comment by Cody2333** [comment]
For compatibility with Babel, we use ES6 modules.
```javascript
// tsconfig.json
  {  "esModuleInterop": true}
```
esModuleInterop need to be open for TS project to use koa-swagger-decorator

**Comment by nirajbisht** [comment]
thanx sir for your support
