### ISSUE TITLE
string checker for null value

### ISSUE THREAD

**Issue by akirapanda** [Cody2333/koa-swagger-decorator#66]
For null value, when I defined the schema as "type:string" then the checker would not allow a field with null value as "{ "field_name":null}  passed.
So I want to ask a question, so as the design of koa-swagger-decorator, a null value is not a string and if we would pass a 'null value', we have to pass '' at least?

**Comment by Cody2333** [comment]
#65 fix this problem by adding a 'nullable' option.
```  
@body({
    a: {
      type: 'string',
      nullable: true
    }
  })
```
