### ISSUE TITLE
pm2支持

### ISSUE THREAD

**Issue by nocoah** [Cody2333/koa-swagger-decorator#70]
请问如果使用pm2启动koa-swagger-decorator，要如何实现？
目前已试过如下方式，但都不行，包括：
`pm2 start my_app.js --node-args="--harmony"`
`创建一个server.js文件，
require('babel-register');
require('babel-polyfill');
require('./app')`
`pm2 start ecosystem.config.js --interpreter babel-node`
以上三种方式都不无法使用pm2运行起来
但这种方式可以：
新建一个server.js
`require('child_process').exec('babel-node bin/www');`
然后pm2运行server.js，可以运行起来
如果查看pm2 log 其实还是报错import的错误
但实际上站点可以运行起来
回归，请问如果使用pm2启动koa-swagger-decorator，要如何实现？

**Comment by Cody2333** [comment]
建议先用 babel 转译一下 js 代码，然后正常用 node 启动就行
