### ISSUE TITLE
responses 中 description 只能输入字符串，不能设置返回的数据

### ISSUE THREAD

**Issue by Tmargin** [Cody2333/koa-swagger-decorator#96]
希望response 能返回数据结构，
像body 一样

**Comment by shentao1** [comment]
+1

**Comment by Cody2333** [comment]
可以参考 swagger 的语法，没有做额外的处理
```
// 定义 swagger 的默认返回格式
export const defaultResponse = {
  403: {
    description: 'Forbidden'
  },
  500: {
    description: 'Internal Server Error'
  },
  200: {
    // response 这里还是遵循 swagger 的语法，没有做额外的封装，因为之前没有特殊的需求要严格定义返回的字段
    // 如果有需求这边也可以做和请求入参一样的封装
    description: 'success',
    schema: {
      // 通过 schema 定义返回的字段格式
      type: 'object',
      properties: {
        status_code: { type: 'number' },
        data: { type: 'object' },
        message: { type: 'string' }
      }
    }
  }
};

```

**Comment by shentao1** [comment]
> 可以参考 swagger 的语法，没有做额外的处理
> 
> ```
> // 定义 swagger 的默认返回格式
> export const defaultResponse = {
>   403: {
>     description: 'Forbidden'
>   },
>   500: {
>     description: 'Internal Server Error'
>   },
>   200: {
>     // response 这里还是遵循 swagger 的语法，没有做额外的封装，因为之前没有特殊的需求要严格定义返回的字段
>     // 如果有需求这边也可以做和请求入参一样的封装
>     description: 'success',
>     schema: {
>       // 通过 schema 定义返回的字段格式
>       type: 'object',
>       properties: {
>         status_code: { type: 'number' },
>         data: { type: 'object' },
>         message: { type: 'string' }
>       }
>     }
>   }
> };
> ```

收到，谢谢。建议文档备注下这个，star一下
