### ISSUE TITLE
关于嵌套路由prefix的问题

### ISSUE THREAD

**Issue by CharNero** [Cody2333/koa-swagger-decorator#97]
koa-swagger-decorator: "^1.6.1"

top = new SwaggerRouter({prefix: '/api'})
1. v1 = new SwaggerRouter({prefix: '/v1'})
    v1.swagger({prefix: '/api/v1'})
    top.use(v1.routes())
    访问嵌套的v1的swagge中swagger-json的路径会解析成/v1/swagger-json，会报错

2. v1 = new SwaggerRouter()
    v1.swagger({prefix: '/api/v1'})
    top.use('/v1', v1.routes())
    如果这样就不会有问题，正常解析为/api/v1/swagger-json

不知道这是个bug，还是我上边的哪里有问题，反正现在用下边这种可以正常访问

**Comment by Cody2333** [comment]
预期是这样的哈，SwaggerRouter 内部感知不到上层路由设置的 prefix
